affinity: {}
develop:
  enabled: false
  repository: nginx
  tag: latest
env: []
envFrom: []
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: alpine
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
