{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pose-estimation-s3-latest-image-web.serviceAccountName" . }}
  labels:
{{ include "pose-estimation-s3-latest-image-web.labels" . | nindent 4 }}
{{- end -}}
